# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
notifications:
  email: false
before_script:
  - julia -e 'Pkg.clone("git://github.com/blegat/StructJuMP.jl.git")'
  - julia -e 'Pkg.clone("git://github.com/blegat/StochasticDualDynamicProgramming.jl.git")'
  - julia -e 'Pkg.add("Clp")'
  - julia -e 'Pkg.add("CDDLib")'
  - julia -e 'Pkg.checkout("CDDLib")'
  - julia -e 'Pkg.checkout("Polyhedra")'
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("InformationTheory"); Pkg.test("InformationTheory"; coverage=true)'
