# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
notifications:
  email: false
before_script:
  - julia -e 'Pkg.clone("https://github.com/blegat/StructDualDynProg.jl.git")'
  - julia -e 'Pkg.clone("https://github.com/JuliaPolyhedra/Polyhedra.jl.git")'
after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("EntropicCone")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("EntropicCone")); include(joinpath("docs", "make.jl"))'
